"""
Bicep template generators for Azure Automation Account.
"""

from typing import Dict


def generate_main_bicep(subscription_id: str, timezone: str, start_time: str, stop_time: str) -> str:
    """Generate main Bicep file for Automation Account."""
    # Using string concatenation to avoid f-string escaping issues
    template = [
        "// Azure Automation Account for VM Snoozing",
        "// Generated by VM Snoozing Agent",
        f"// Subscription: {subscription_id}",
        "",
        "@description('Location for all resources')",
        "param location string = resourceGroup().location",
        "",
        "@description('Name of the Automation Account')",
        "param automationAccountName string = 'snooze-automation-${uniqueString(subscription().subscriptionId)}'",
        "",
        "@description('Pricing tier')",
        "param sku string = 'Basic'",
        "",
        "@description('Tags for resources')",
        "param tags object = {",
        "  managedBy: 'vm-snoozing-agent'",
        "  environment: 'nonprod'",
        "  purpose: 'vm-snoozing'",
        "}",
        "",
        "// Automation Account",
        "resource automationAccount 'Microsoft.Automation/automationAccounts@2022-08-08' = {",
        "  name: automationAccountName",
        "  location: location",
        "  tags: tags",
        "  identity: {",
        "    type: 'SystemAssigned'",
        "  }",
        "  properties: {",
        "    sku: {",
        "      name: sku",
        "    }",
        "    encryption: {",
        "      keySource: 'Microsoft.Automation'",
        "    }",
        "  }",
        "}",
        "",
        "// Stop VMs Runbook",
        "resource stopVMsRunbook 'Microsoft.Automation/automationAccounts/runbooks@2022-08-08' = {",
        "  parent: automationAccount",
        "  name: 'Stop-TargetedVMs'",
        "  location: location",
        "  tags: tags",
        "  properties: {",
        "    runbookType: 'PowerShell'",
        "    logProgress: true",
        "    logVerbose: true",
        "    description: 'Stops VMs based on tag selector outside business hours'",
        "  }",
        "}",
        "",
        "// Start VMs Runbook",
        "resource startVMsRunbook 'Microsoft.Automation/automationAccounts/runbooks@2022-08-08' = {",
        "  parent: automationAccount",
        "  name: 'Start-TargetedVMs'",
        "  location: location",
        "  tags: tags",
        "  properties: {",
        "    runbookType: 'PowerShell'",
        "    logProgress: true",
        "    logVerbose: true",
        "    description: 'Starts VMs based on tag selector during business hours'",
        "  }",
        "}",
        "",
        f"// Schedule for stopping VMs (e.g., {stop_time} {timezone} Mon-Fri)",
        "resource stopSchedule 'Microsoft.Automation/automationAccounts/schedules@2022-08-08' = {",
        "  parent: automationAccount",
        "  name: 'StopVMsSchedule'",
        "  properties: {",
        f"    description: 'Schedule to stop VMs at {stop_time} {timezone}'",
        "    startTime: dateTimeAdd(utcNow(), 'PT1H')",
        "    expiryTime: '9999-12-31T23:59:59.9999999Z'",
        "    interval: 1",
        "    frequency: 'Day'",
        f"    timeZone: '{timezone}'",
        "    advancedSchedule: {",
        "      weekDays: [",
        "        'Monday'",
        "        'Tuesday'",
        "        'Wednesday'",
        "        'Thursday'",
        "        'Friday'",
        "      ]",
        "    }",
        "  }",
        "}",
        "",
        f"// Schedule for starting VMs (e.g., {start_time} {timezone} Mon-Fri)",
        "resource startSchedule 'Microsoft.Automation/automationAccounts/schedules@2022-08-08' = {",
        "  parent: automationAccount",
        "  name: 'StartVMsSchedule'",
        "  properties: {",
        f"    description: 'Schedule to start VMs at {start_time} {timezone}'",
        "    startTime: dateTimeAdd(utcNow(), 'PT1H')",
        "    expiryTime: '9999-12-31T23:59:59.9999999Z'",
        "    interval: 1",
        "    frequency: 'Day'",
        f"    timeZone: '{timezone}'",
        "    advancedSchedule: {",
        "      weekDays: [",
        "        'Monday'",
        "        'Tuesday'",
        "        'Wednesday'",
        "        'Thursday'",
        "        'Friday'",
        "      ]",
        "    }",
        "  }",
        "}",
        "",
        "// Link Stop Runbook to Schedule",
        "resource stopJobSchedule 'Microsoft.Automation/automationAccounts/jobSchedules@2022-08-08' = {",
        "  parent: automationAccount",
        "  name: guid(automationAccount.id, stopSchedule.name, stopVMsRunbook.name)",
        "  properties: {",
        "    runbook: {",
        "      name: stopVMsRunbook.name",
        "    }",
        "    schedule: {",
        "      name: stopSchedule.name",
        "    }",
        "  }",
        "}",
        "",
        "// Link Start Runbook to Schedule",
        "resource startJobSchedule 'Microsoft.Automation/automationAccounts/jobSchedules@2022-08-08' = {",
        "  parent: automationAccount",
        "  name: guid(automationAccount.id, startSchedule.name, startVMsRunbook.name)",
        "  properties: {",
        "    runbook: {",
        "      name: startVMsRunbook.name",
        "    }",
        "    schedule: {",
        "      name: startSchedule.name",
        "    }",
        "  }",
        "}",
        "",
        "// Outputs",
        "output automationAccountId string = automationAccount.id",
        "output automationAccountName string = automationAccount.name",
        "output principalId string = automationAccount.identity.principalId",
        "output stopRunbookName string = stopVMsRunbook.name",
        "output startRunbookName string = startVMsRunbook.name",
    ]
    return "\n".join(template)


def generate_parameters_bicepparam(subscription_id: str) -> str:
    """Generate Bicep parameters file."""
    return f"""// Parameters for VM Snoozing Automation Account
// Subscription: {subscription_id}

using './main.bicep'

param location = 'westeurope'
param automationAccountName = 'snooze-automation-{subscription_id[:8]}'
param sku = 'Basic'
param tags = {{
  managedBy: 'vm-snoozing-agent'
  environment: 'nonprod'
  purpose: 'vm-snoozing'
  subscription: '{subscription_id}'
}}
"""


def generate_stop_runbook(tag_selector: Dict) -> str:
    """Generate PowerShell runbook for stopping VMs."""
    tag_lines = "\n".join([
        f'    "{key}" = "{value}"'
        for key, value in tag_selector.items()
    ]) if tag_selector else '    # No tags specified'
    
    tag_conditions = " -and ".join([
        f'$vm.Tags["{key}"] -eq "{value}"'
        for key, value in tag_selector.items()
    ]) if tag_selector else '$true'
    
    return f'''<#
.SYNOPSIS
    Stops Azure VMs based on tag selector.

.DESCRIPTION
    This runbook stops VMs that match the specified tag criteria.
    Uses Managed Identity for authentication.

.NOTES
    Generated by VM Snoozing Agent
#>

param()

# Connect to Azure using Managed Identity
try {{
    Write-Output "Connecting to Azure using Managed Identity..."
    Connect-AzAccount -Identity -ErrorAction Stop
    Write-Output "Successfully connected to Azure"
}}
catch {{
    Write-Error "Failed to connect to Azure: $_"
    throw
}}

# Get subscription context
$context = Get-AzContext
Write-Output "Current subscription: $($context.Subscription.Name) ($($context.Subscription.Id))"

# Define tag selector
$tagSelector = @{{
{tag_lines}
}}

Write-Output "Searching for VMs with tags: $($tagSelector | ConvertTo-Json -Compress)"

# Get all VMs in subscription
$allVMs = Get-AzVM -Status

# Filter VMs based on tags
$targetVMs = $allVMs | Where-Object {{
    $vm = $_
    {tag_conditions}
}}

Write-Output "Found $($targetVMs.Count) VMs matching criteria"

# Stop each VM
$results = @()
foreach ($vm in $targetVMs) {{
    Write-Output "Processing VM: $($vm.Name) in Resource Group: $($vm.ResourceGroupName)"
    Write-Output "  Current Status: $($vm.PowerState)"
    
    if ($vm.PowerState -eq "VM running") {{
        try {{
            Write-Output "  Stopping VM..."
            Stop-AzVM -ResourceGroupName $vm.ResourceGroupName -Name $vm.Name -Force -NoWait
            $results += [PSCustomObject]@{{
                VMName = $vm.Name
                ResourceGroup = $vm.ResourceGroupName
                Action = "Stop"
                Status = "Success"
            }}
            Write-Output "  Stop command issued successfully"
        }}
        catch {{
            Write-Error "  Failed to stop VM: $_"
            $results += [PSCustomObject]@{{
                VMName = $vm.Name
                ResourceGroup = $vm.ResourceGroupName
                Action = "Stop"
                Status = "Failed"
                Error = $_.Exception.Message
            }}
        }}
    }}
    else {{
        Write-Output "  VM is not running, skipping"
        $results += [PSCustomObject]@{{
            VMName = $vm.Name
            ResourceGroup = $vm.ResourceGroupName
            Action = "Skip"
            Status = "Not Running"
        }}
    }}
}}

# Output summary
Write-Output "`nSummary:"
Write-Output "========="
$results | Format-Table -AutoSize
Write-Output "`nRunbook completed"
'''


def generate_start_runbook(tag_selector: Dict) -> str:
    """Generate PowerShell runbook for starting VMs."""
    tag_lines = "\n".join([
        f'    "{key}" = "{value}"'
        for key, value in tag_selector.items()
    ]) if tag_selector else '    # No tags specified'
    
    tag_conditions = " -and ".join([
        f'$vm.Tags["{key}"] -eq "{value}"'
        for key, value in tag_selector.items()
    ]) if tag_selector else '$true'
    
    return f'''<#
.SYNOPSIS
    Starts Azure VMs based on tag selector.

.DESCRIPTION
    This runbook starts VMs that match the specified tag criteria.
    Uses Managed Identity for authentication.

.NOTES
    Generated by VM Snoozing Agent
#>

param()

# Connect to Azure using Managed Identity
try {{
    Write-Output "Connecting to Azure using Managed Identity..."
    Connect-AzAccount -Identity -ErrorAction Stop
    Write-Output "Successfully connected to Azure"
}}
catch {{
    Write-Error "Failed to connect to Azure: $_"
    throw
}}

# Get subscription context
$context = Get-AzContext
Write-Output "Current subscription: $($context.Subscription.Name) ($($context.Subscription.Id))"

# Define tag selector
$tagSelector = @{{
{tag_lines}
}}

Write-Output "Searching for VMs with tags: $($tagSelector | ConvertTo-Json -Compress)"

# Get all VMs in subscription
$allVMs = Get-AzVM -Status

# Filter VMs based on tags
$targetVMs = $allVMs | Where-Object {{
    $vm = $_
    {tag_conditions}
}}

Write-Output "Found $($targetVMs.Count) VMs matching criteria"

# Start each VM
$results = @()
foreach ($vm in $targetVMs) {{
    Write-Output "Processing VM: $($vm.Name) in Resource Group: $($vm.ResourceGroupName)"
    Write-Output "  Current Status: $($vm.PowerState)"
    
    if ($vm.PowerState -ne "VM running") {{
        try {{
            Write-Output "  Starting VM..."
            Start-AzVM -ResourceGroupName $vm.ResourceGroupName -Name $vm.Name -NoWait
            $results += [PSCustomObject]@{{
                VMName = $vm.Name
                ResourceGroup = $vm.ResourceGroupName
                Action = "Start"
                Status = "Success"
            }}
            Write-Output "  Start command issued successfully"
        }}
        catch {{
            Write-Error "  Failed to start VM: $_"
            $results += [PSCustomObject]@{{
                VMName = $vm.Name
                ResourceGroup = $vm.ResourceGroupName
                Action = "Start"
                Status = "Failed"
                Error = $_.Exception.Message
            }}
        }}
    }}
    else {{
        Write-Output "  VM is already running, skipping"
        $results += [PSCustomObject]@{{
            VMName = $vm.Name
            ResourceGroup = $vm.ResourceGroupName
            Action = "Skip"
            Status = "Already Running"
        }}
    }}
}}

# Output summary
Write-Output "`nSummary:"
Write-Output "========="
$results | Format-Table -AutoSize
Write-Output "`nRunbook completed"
'''
