"""
Terraform template generators for Azure Automation Account.
"""

from typing import Dict


def generate_main_tf(subscription_id: str, timezone: str, start_time: str, stop_time: str) -> str:
    """Generate main Terraform file for Automation Account."""
    # Build template without f-string to avoid escaping issues
    lines = [
        "# Azure Automation Account for VM Snoozing",
        "# Generated by VM Snoozing Agent",
        f"# Subscription: {subscription_id}",
        "",
        "terraform {",
        "  required_providers {",
        "    azurerm = {",
        '      source  = "hashicorp/azurerm"',
        '      version = "~> 3.0"',
        "    }",
        "  }",
        "}",
        "",
        'provider "azurerm" {',
        "  features {}",
        "}",
        "",
        "# Data source for current subscription",
        'data "azurerm_subscription" "current" {}',
        "",
        "# Data source for client config",
        'data "azurerm_client_config" "current" {}',
        "",
        "# Resource Group (assuming it already exists)",
        'data "azurerm_resource_group" "snooze" {',
        "  name = var.resource_group_name",
        "}",
        "",
        "# Automation Account",
        'resource "azurerm_automation_account" "snooze" {',
        '  name                = "snooze-automation-${substr(md5(data.azurerm_subscription.current.id), 0, 8)}"',
        "  location            = data.azurerm_resource_group.snooze.location",
        "  resource_group_name = data.azurerm_resource_group.snooze.name",
        '  sku_name            = "Basic"',
        "",
        "  identity {",
        '    type = "SystemAssigned"',
        "  }",
        "",
        "  tags = {",
        '    managedBy   = "vm-snoozing-agent"',
        '    environment = "nonprod"',
        '    purpose     = "vm-snoozing"',
        "  }",
        "}",
        "",
        "# Stop VMs Runbook",
        'resource "azurerm_automation_runbook" "stop_vms" {',
        '  name                    = "Stop-TargetedVMs"',
        "  location                = data.azurerm_resource_group.snooze.location",
        "  resource_group_name     = data.azurerm_resource_group.snooze.name",
        "  automation_account_name = azurerm_automation_account.snooze.name",
        "  log_verbose             = true",
        "  log_progress            = true",
        '  description             = "Stops VMs based on tag selector outside business hours"',
        '  runbook_type            = "PowerShell"',
        "",
        '  content = file("${path.module}/runbooks/Stop-TargetedVMs.ps1")',
        "",
        "  tags = {",
        '    managedBy = "vm-snoozing-agent"',
        '    purpose   = "vm-stop"',
        "  }",
        "}",
        "",
        "# Start VMs Runbook",
        'resource "azurerm_automation_runbook" "start_vms" {',
        '  name                    = "Start-TargetedVMs"',
        "  location                = data.azurerm_resource_group.snooze.location",
        "  resource_group_name     = data.azurerm_resource_group.snooze.name",
        "  automation_account_name = azurerm_automation_account.snooze.name",
        "  log_verbose             = true",
        "  log_progress            = true",
        '  description             = "Starts VMs based on tag selector during business hours"',
        '  runbook_type            = "PowerShell"',
        "",
        '  content = file("${path.module}/runbooks/Start-TargetedVMs.ps1")',
        "",
        "  tags = {",
        '    managedBy = "vm-snoozing-agent"',
        '    purpose   = "vm-start"',
        "  }",
        "}",
        "",
        f"# Schedule for stopping VMs (e.g., {stop_time} {timezone} Mon-Fri)",
        'resource "azurerm_automation_schedule" "stop_schedule" {',
        '  name                    = "StopVMsSchedule"',
        "  resource_group_name     = data.azurerm_resource_group.snooze.name",
        "  automation_account_name = azurerm_automation_account.snooze.name",
        '  frequency               = "Day"',
        "  interval                = 1",
        f'  timezone                = "{timezone}"',
        '  start_time              = timeadd(timestamp(), "1h")',
        f'  description             = "Schedule to stop VMs at {stop_time} {timezone}"',
        '  week_days               = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]',
        "}",
        "",
        f"# Schedule for starting VMs (e.g., {start_time} {timezone} Mon-Fri)",
        'resource "azurerm_automation_schedule" "start_schedule" {',
        '  name                    = "StartVMsSchedule"',
        "  resource_group_name     = data.azurerm_resource_group.snooze.name",
        "  automation_account_name = azurerm_automation_account.snooze.name",
        '  frequency               = "Day"',
        "  interval                = 1",
        f'  timezone                = "{timezone}"',
        '  start_time              = timeadd(timestamp(), "1h")',
        f'  description             = "Schedule to start VMs at {start_time} {timezone}"',
        '  week_days               = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]',
        "}",
        "",
        "# Link Stop Runbook to Schedule",
        'resource "azurerm_automation_job_schedule" "stop_job_schedule" {',
        "  resource_group_name     = data.azurerm_resource_group.snooze.name",
        "  automation_account_name = azurerm_automation_account.snooze.name",
        "  runbook_name            = azurerm_automation_runbook.stop_vms.name",
        "  schedule_name           = azurerm_automation_schedule.stop_schedule.name",
        "",
        "  parameters = {",
        "    # Add parameters here if needed",
        "  }",
        "}",
        "",
        "# Link Start Runbook to Schedule",
        'resource "azurerm_automation_job_schedule" "start_job_schedule" {',
        "  resource_group_name     = data.azurerm_resource_group.snooze.name",
        "  automation_account_name = azurerm_automation_account.snooze.name",
        "  runbook_name            = azurerm_automation_runbook.start_vms.name",
        "  schedule_name           = azurerm_automation_schedule.start_schedule.name",
        "",
        "  parameters = {",
        "    # Add parameters here if needed",
        "  }",
        "}",
        "",
        "# Role assignment for VM operations (Contributor role on subscription)",
        'resource "azurerm_role_assignment" "automation_vm_ops" {',
        "  scope                = data.azurerm_subscription.current.id",
        '  role_definition_name = "Virtual Machine Contributor"',
        "  principal_id         = azurerm_automation_account.snooze.identity[0].principal_id",
        "}",
    ]
    return "\n".join(lines)


def generate_variables_tf() -> str:
    """Generate Terraform variables file."""
    return '''# Variables for VM Snoozing Automation

variable "resource_group_name" {
  description = "Name of the resource group for the Automation Account"
  type        = string
}

variable "location" {
  description = "Azure region for resources"
  type        = string
  default     = "westeurope"
}

variable "tags" {
  description = "Tags to apply to all resources"
  type        = map(string)
  default = {
    managedBy   = "vm-snoozing-agent"
    environment = "nonprod"
    purpose     = "vm-snoozing"
  }
}
'''


def generate_outputs_tf() -> str:
    """Generate Terraform outputs file."""
    return '''# Outputs for VM Snoozing Automation

output "automation_account_id" {
  description = "ID of the Automation Account"
  value       = azurerm_automation_account.snooze.id
}

output "automation_account_name" {
  description = "Name of the Automation Account"
  value       = azurerm_automation_account.snooze.name
}

output "principal_id" {
  description = "Principal ID of the Automation Account managed identity"
  value       = azurerm_automation_account.snooze.identity[0].principal_id
}

output "stop_runbook_name" {
  description = "Name of the Stop VMs runbook"
  value       = azurerm_automation_runbook.stop_vms.name
}

output "start_runbook_name" {
  description = "Name of the Start VMs runbook"
  value       = azurerm_automation_runbook.start_vms.name
}

output "stop_schedule_name" {
  description = "Name of the stop schedule"
  value       = azurerm_automation_schedule.stop_schedule.name
}

output "start_schedule_name" {
  description = "Name of the start schedule"
  value       = azurerm_automation_schedule.start_schedule.name
}
'''


def generate_stop_runbook(tag_selector: Dict) -> str:
    """Generate PowerShell runbook for stopping VMs (same as Bicep)."""
    # Reuse from bicep_templates
    from templates.bicep_templates import generate_stop_runbook as bicep_stop
    return bicep_stop(tag_selector)


def generate_start_runbook(tag_selector: Dict) -> str:
    """Generate PowerShell runbook for starting VMs (same as Bicep)."""
    # Reuse from bicep_templates
    from templates.bicep_templates import generate_start_runbook as bicep_start
    return bicep_start(tag_selector)
